<<<
[appendix]

== Web Mapping API examples

This Appendix provides several examples of web mapping APIs.
This Appendix is referenced in Chapter 2 on API Design.

* Google Maps

* OpenLayers

* MapQuest API for OpenStreetMap

* Leaflet

* Esri ArcGIS REST

* Mapbox



[float]
==== Google Maps

https://developers.google.com/maps[Google Maps APIs] are available for Android, iOS, web browsers in Javascript and via HTTP web services.
The Google Maps API pulls from Google Map servers and may be configured to pull from other servers.

The https://developers.google.com/maps/documentation/javascript/[Google Maps JavaScript API] includes a constructor "Map" class,
20 methods, 4 properties and multiple events.
Objects of the google.maps.Map class define a single map on a page.
There are two required options for every map: "center" and `"zoom". For example:
----
map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: -34.397, lng: 150.644},
  zoom: 8
});
----

Zoom is a number where zoom "0" corresponds to a map of the Earth fully zoomed out,
and larger zoom levels zoom in at a higher resolution.

Center is of type https://developers.google.com/maps/documentation/javascript/reference#LatLng[LatLng]
which is a point in geographical coordinates: latitude and longitude.
This cautionary note is provided: "Although the default map projection associates longitude with the x-coordinate of the map,
and latitude with the y-coordinate, the latitude coordinate is always written__first__, followed by the longitude.
A separate page describes https://developers.google.com/maps/documentation/javascript/maptypes#MapCoordinates[MapCoordinates] including the use of https://en.wikipedia.org/wiki/World_Geodetic_System[World Geodetic System WGS84]
and https://en.wikipedia.org/wiki/Mercator_projection[Mercator projection].


[float]
==== OpenLayers

http://openlayers.org/[OpenLayers] is an open source library for displaying map data in web browsers.
Open Layers can pull tiles from OSM, Bing, MapBox, Stamen, MapQuest and other sources.
The OGC Web Services are supported.

The core component of OpenLayers 3 is the map (ol.Map).
For a map to render, a view, one or more layers, and a target container are needed:

[source,java]
----
var map = new ol.Map({
  view: new ol.View({
    center: [0, 0],
    zoom: 1
  }),
  layers: [
    new ol.layer.Tile({
      source: new ol.source.MapQuest({layer: 'osm'})
    })
  ],
  target: 'map'
});
----

The above snippet creates a map using a http://openlayers.org/en/v3.13.0/apidoc/ol.layer.Tile.html[``ol.layer.Tile``]
to display http://openlayers.org/en/v3.13.0/apidoc/ol.source.MapQuest.html[``ol.source.MapQuest``] OSM data
and render it to a DOM element with the id ``map``.

An ol.View has a projection that determines the coordinate system of the center and the units for map resolution calculations.
If not specified, the default projection is Spherical Mercator (EPSG:3857), with meters as map units.

The zoom option is a convenient way to specify the map resolution.
The available zoom levels are determined by maxZoom (default: 28), zoomFactor (default: 2) and maxResolution.

[float]
==== MapQuest API for OpenStreetMap

http://open.mapquestapi.com/staticmap/#getmap[The MapQuest Open API] accesses MapQuest Open tiles (made from OSM data).
The method ``"getmap"`` takes a latitude/longitude pair and will center the static map image over that center point.

[source,java]
----
var SAMPLE_POST = HOST_URL + '/staticmap/v4/getmap?key=YOUR_KEY_HERE&size=400,200&zoom=10&center=40.0378,-76.305801';

function showBasicURL() {
    var safe = SAMPLE_POST;
    document.getElementById('basicSampleUrl').innerHTML = safe.replace(/</g, '<').replace(/>/g, '>');;
};

function doClick() {
    var newURL = SAMPLE_POST.replace('YOUR_KEY_HERE', APP_KEY);
    document.getElementById('basicImage').innerHTML = '';
};
----
|=======================
| Request Parameter | Description | Example Request Data
| center | A center point for the map image. | 40.039401,-76.307078
| zoom | Specifies zoom level for the map image. | A valid zoom integer. See http://open.mapquestapi.com/staticmap/zoomToScale.html[Zoom to Scale Mapping] for information on scales versus zoom levels.

|=======================

[float]
==== Leaflet

http://leafletjs.com/[Leaflet] is an open-source JavaScript library for interactive maps.
L.map is the central class of the http://leafletjs.com/reference-1.0.0.html[Leaflet API]
used to create a map on a page and manipulate it.
http://leafletjs.com/reference-1.0.0.html#tilelayer-wms[TileLayer.WMS] is used
to display WMS services as tile layers on the map.

Example of Leaflet Map class:
[source,java]
----
// initialize the map on the "map" div with a given center and zoom
var map = L.map('map', {
    center: [51.505, -0.09],
    zoom: 13
});
----

|====
| Factory | Description
| **L.map** (<HTMLElement String> id, <http://leafletjs.com/reference-1.0.0.html#map-options[Map options]> options? ) | Instantiates a map object given a div element (or its id) and optionally an object literal with map options described below.
|====

Two of the Map State Options

|====
| Option | Type | Default | Description
| **center** | http://leafletjs.com/reference-1.0.0.html#latlng[LatLng] | null | Initial geographical center of the map.
| **zoom** | Number | null | Initial map zoom.
|====

The LatLng type is a geographical point with a latitude and longitude.
No CRS is identify in the Leaflet API page for the LatLng coordinates.


[float]
=== Esri ArcGIS REST

http://resources.arcgis.com/en/help/arcgis-rest-api/index.html[The ArcGIS REST API] offers resources for working
within a Portal for ArcGIS implementation or within ArcGIS Online.
http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Map_Service/02r3000000w2000000/[The Map Service]
offers access to contents of a map hosted on a server.
http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Export_Map/02r3000000v7000000/[Export Map] operation
is peformed on a map service resource and returns a map image.

Example Usage: Export a map. Include only the bounding box.
----
http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Specialty/ESRI_StateCityHighway_USA/MapServer/export?bbox=-127.8,15.4,-63.5,60.5=
----

Example Request Parameter in Esri ArcGIS REST

|====
| Parameter | Details
| bbox | Description: (Required) The extent (bounding box) of the exported image. Unless the bboxSR parameter has been specified, the bbox is assumed to be in the spatial reference of the map.

Syntax: <xmin>, <ymin>, <xmax>, <ymax>

Example: bbox=-104,35.6,-94.32,41

The bbox coordinates should always use a period as the decimal separator even in countries where traditionally a comma is used.
|====
[float]
=== Mapbox

https://www.mapbox.com/developers/api/[Mapbox web services] accept ``GET`` requests and support both HTTP and HTTPS.
Access to Mapbox web services requires an access token, which connects API requests to an account.

https://www.mapbox.com/developers/api/static/[Mapbox static maps] are standalone images that can be displayed on web
and mobile devices.

----
https://api.mapbox.com/v4/{mapid}/{lon},{lat},{z}/{width}x{height}.{format}?access_token=<your access token>
https://api.mapbox.com/v4/{mapid}/{overlay}/{lon},{lat},{z}/{width}x{height}.{format}?access_token=<your access token>
https://api.mapbox.com/v4/{mapid}/{overlay}/auto/{width}x{height}.{format}?access_token=<your access token>
----

----
Examples
https://api.mapbox.com/v4/mapbox.streets/-73.99,40.70,13/500x300.png?access_token=<your%20access%20token>
https://api.mapbox.com/v4/mapbox.streets/pin-s-bus+f44(-73.99,40.70,13)/-73.99,40.70,13/500x300.png?access_token=<your%20access%20token>
----

https://www.mapbox.com/developers/api/maps/#tiles[Mapbox tile maps] request a 256x256 image tile or UTFGrid for a given {mapid}. The {z}, {x}, and {y} parameters must be integer coordinates describing the tile position according to the XYZ tiling scheme. The tile {format}defaults to png but can be used to adjust the image quality, format, and scale factor.

----
https://api.mapbox.com/v4/{mapid}/{z}/{x}/{y}.{format}?access_token=<your access token>
----

----
Examples
https://api.mapbox.com/v4/mapbox.streets/0/0/0.png?access_token=<your%20access%20token>
https://api.mapbox.com/v4/mapbox.streets/0/0/0.jpg?access_token=<your%20access%20token>
https://api.mapbox.com/v4/mapbox.edf947b8/5/6/11.grid.json?access_token=<your%20access%20token>
----
