= OGC® Open Geospatial APIs - White Paper
Open Geospatial Consortium Document OGC 16-019r1

:doctype: book
:encoding: utf-8
:lang: en
:toc: left
:toclevels: 1
:numbered:

*OGC® Open Geospatial APIs - White Paper*

External identifier of this OGC® document: TBD +
URL for this OGC® document: TBD +
Internal reference number of this OGC® document: OGC 16-019r1 +
Version: +
Category: OGC® White Paper  +
Editor: George Percivall +
Previous Version:  +
Publication Date: 2016-TBD +
Approval Date: 2016-TBD +
Submission Date:   +

Copyright © 2016 Open Geospatial Consortium.  

To obtain additional rights of use, visit http://www.opengeospatial.org/legal/[http://www.opengeospatial.org/legal/]  

**Warning**

This document is not an OGC Standard. This document is an OGC White Paper and is therefore not an official position of the OGC membership. It is distributed for review and comment. It is subject to change without notice and may not be referred to as an OGC Standard. Further, an OGC White Paper should not be referenced as required or mandatory technology in procurements


Document type: OGC® White Paper  
Document stage: Prepared for review at OGC TC June 2016  
Document language: English



include::preface.adoc[]

include::chapter-01.adoc[]

include::chapter-02.adoc[]

include::chapter-03.adoc[]

include::chapter-04.adoc[]

include::chapter-05.adoc[]

include::annex-a.adoc[]

 
