= Chapter 2. Web Mapping API examples 

== Web mapping APIs

Web mapping APIs provide access to maps over the web.  They are Client-side WebAPIs as defined in the prevoius chapter.  While web maping APIs are defined in multiple programming languages, the examples here focus on Javascript.

APIs for web mapping was the topic of a recent posting by http://www.programmableweb.com/news/top-10-mapping-apis-google-maps-microsoft-bing-maps-and-mapquest/analysis/2015/02/23[The Programmable Web] with the "top ten" being: Google Maps, Microsoft Bing Maps, OpenLayers, Foursquare, OpenStreetMap, MapQuest, Mapbox, CartoDB, Esri, and Yahoo. 

Most the the APIs listed below implement the OWS Protocols either explicitly or the API provides an extension method for adding protocols.

== Google Maps

https://developers.google.com/maps[Google Maps APIs] are available for Android, iOS, web browsers in Javascript and via HTTP web services.  The Google Maps API pulls from Google Map servers and may be configured to pull from other servers.

The https://developers.google.com/maps/documentation/javascript/[Google Maps JavaScript API] includes a constructor "Map" class, 20 methods, 4 properties and multiple events.  Objects of the google.maps.Map class define a single map on a page. There are two required options for every map: "center" and `"zoom". For example:
----
map = new google.maps.Map(document.getElementById('map'), {  
  center: {lat: -34.397, lng: 150.644},  
  zoom: 8  
});
----

Zoom is a number where zoom "0" corresponds to a map of the Earth fully zoomed out, and larger zoom levels zoom in at a higher resolution.

Center is of type https://developers.google.com/maps/documentation/javascript/reference#LatLng[LatLng] which is a point in geographical coordinates: latitude and longitude. This cautionary note is provided: "Although the default map projection associates longitude with the x-coordinate of the map, and latitude with the y-coordinate, the latitude coordinate is always written__first__, followed by the longitude. A separate page describes https://developers.google.com/maps/documentation/javascript/maptypes#MapCoordinates[MapCoordinates] including the use of https://en.wikipedia.org/wiki/World_Geodetic_System[World Geodetic System WGS84] and  https://en.wikipedia.org/wiki/Mercator_projection[Mercator projection].

== OpenLayers

http://openlayers.org/[OpenLayers] is an open source library for displaying map data in web browsers.  Open Layers can pull tiles from OSM, Bing, MapBox, Stamen, MapQuest and other sources. The OGC Web Map Services are supported.

The core component of OpenLayers 3 is the map (ol.Map). For a map to render, a view, one or more layers, and a target container are needed:

[source,java]
----
var map = new ol.Map({
  view: new ol.View({
    center: [0, 0],
    zoom: 1
  }),
  layers: [
    new ol.layer.Tile({
      source: new ol.source.MapQuest({layer: 'osm'})
    })
  ],
  target: 'map'
});
----

The above snippet creates a map using a http://openlayers.org/en/v3.13.0/apidoc/ol.layer.Tile.html[``ol.layer.Tile``] to display http://openlayers.org/en/v3.13.0/apidoc/ol.source.MapQuest.html[``ol.source.MapQuest``] OSM data and render it to a DOM element with the id ``map``.

An ol.View has a projection that determines the coordinate system of the center and the units for map resolution calculations. If not specified, the default projection is Spherical Mercator (EPSG:3857), with meters as map units.

The zoom option is a convenient way to specify the map resolution. The available zoom levels are determined by maxZoom (default: 28), zoomFactor (default: 2) and maxResolution. 

== MapQuest API for OpenStreetMap

http://open.mapquestapi.com/staticmap/#getmap[The MapQuest Open API] accesses 
MapQuest Open tiles (made from OSM data). The method ``"getmap"`` takes a latitude/longitude pair and will center the static map image over that center point. 

[source,java]
----
var SAMPLE_POST = HOST_URL + '/staticmap/v4/getmap?key=YOUR_KEY_HERE&size=400,200&zoom=10&center=40.0378,-76.305801';

function showBasicURL() {
    var safe = SAMPLE_POST;
    document.getElementById('basicSampleUrl').innerHTML = safe.replace(/</g, '<').replace(/>/g, '>');;
};

function doClick() {
    var newURL = SAMPLE_POST.replace('YOUR_KEY_HERE', APP_KEY);
    document.getElementById('basicImage').innerHTML = '';
};
----

== Mapbox

Tiles

[source,java]
----
https://api.mapbox.com/v4/{mapid}/{z}/{x}/{y}.{format}?access_token=<your access token>

----

[source,java]
----
Examples
https://api.mapbox.com/v4/mapbox.streets/0/0/0.png?access_token=<your%20access%20token>
https://api.mapbox.com/v4/mapbox.streets/0/0/0.jpg?access_token=<your%20access%20token>
https://api.mapbox.com/v4/mapbox.edf947b8/5/6/11.grid.json?access_token=<your%20access%20token>

----

Request a 256x256 image tile or UTFGrid for a given {mapid}. The {z}, {x}, and {y} parameters must be integer coordinates describing the tile position according to the XYZ tiling scheme. The tile {format}defaults to png but can be used to adjust the image quality, format, and scale factor.

