== Not USED

OGC APIs

=== OWS Lib

https://github.com/geopython/OWSLib

=== SensorThings

http://www.sensorup.com/docs/#get45

=== Web Map Service and WMTS as an API

http://docs.opengeospatial.org/is/13-082r2/13-082r2.html[WMTS Simple] 

This profile targets implementation by simple RESTful clients that assume a Web Mercator TileMatrixSet (or a World CRS84 TileMatrixSet), ignores the WMTS ServiceMetadata document entirely they are provided with tile-URL templates as inputs, with all but {TileMatrix}, {TileCol} and {TileRow} resolved. The tile URL templates include, as literals, the base URL of the server, the name of the desired layer, TileMatrixSet information, possible style information, the index ordering that the server expects and an indication of the desired file format. A layer in a WMTS server conformant to this simple profile can be advertised by email, a website or any other means by providing a text like this:

----
A WMTS 1.0.0 service that can be accessed with a standard WMTS client application at (http://mycompany.com/wmts) using the WMTS simple profile, with the following templates:

The ‘Oceans’ layer:
http://mycompany.com/wmts/1.0.0/tiles/oceans/default/smerc/{TileMatrix}/{TileCol}/{TileRow}.png

The ‘Transportation’ layer (Rand-McNally style):
http://mycompany.com/wmts/1.0.0/tiles/transportation/RandMcNally/smerc/{TileMatrix}/{TileCol}/{TileRow}.png”
----

== API Wrapping pattern

That's certainly our approach at Planet - make sure that both work well against our (web) API. CartoDB just wraps leaflet with more functionality, and I think Ordnance Survey similarly wraps Openlayers and then combines it with our data.  

Similarly OGC needs to consider CMAPI - a library built on Ozone for DOD: http://cmapi.org/
These libraries expose Library APIs as local process interfaces and use WebAPIs for reaching web services.




== "API Design is Stuck in 2008"

[http://blog.programmableweb.com/2013/10/07/api-design-is-stuck-in-2008/]   [Richardson] has observed "The thousands of APIs created over the past seven years are superficially similar but mutually incompatible. Everyone has a slightly different view of basic real-world concepts like “person” and “event”. This lack of agreement makes it impossible to create client-side software that can be reused between APIs. It’s not hard to find two APIs that do exactly the same thing but have nothing in common except the application/json media type."

CGO could aid the API discussion by providing small reusable peices.  This would aid the marketplace and increase the accuracy of information shared between indendepnt implementations.

===  B11 REST ER

TB12 REST ER assessment of WMS and WMTS as Restful APIs

From Josh Lieberman:

There are two senses in which there term API seems to be used. One is the most basic definition supported by the service being invoked. In the case of REST, that is generally the HTTP requests and responses. This sounds like a service interface, but in the context of REST it’s useful to call this an API, since the most extreme forms of Fielding-defined REST presume that all of the application logic also comes from the server. We wanted to consider REST API’s as building blocks of applications that are themselves not necessarily defined by the REST service, i.e. the way that OGC (and most everyone else) views Web services.

The other sense is the adaptation of that basic interface into another application programming technology, such as a toolkit that enables a Java or Python developer to use procedure or function calls to drive the HTTP interaction. The term API is used both for the language specific interface, and for the code that implements it. That definitely gets confusing. So code samples either comprising such a toolkit or invoking it are useful for developer guidance but only if it is made clear that they aren't how the service API is fundamentally defined. That said, 15-052 is definitely only a preliminary work. The question is how to follow up on it.
