== OGC essentials for APIs

=== The Idea of OGC API Essentials

OGC API Essentials are a small subset of the capabilities defined in OGC standards which would be very useful to developers for the Internet and Web of geospatial information.  

Discussions within the OGC have identified value in recommending small bits of OGC specifications for API providers to use.  Many OGC standards are already modular.  As an alternative to requiring a full-fledged service interface, the OGC API Essentials highlight how modules, such as Well Known Text, GeoJSON, WMTS, CQL/Filter, GeoPackage, etc. are useful in building Web API's. 

This approach identifies pieces that are standardized and easy to use.  It is anticipated that this will raise awareness of OGC in API providers.  Reuse of OGC API Essentials will lead to consistency, accuracy and reuse across the various APIs. And ideally there are lots of small client libraries that can be incorporated in to the libraries API producers provide.

=== OGC API Essentials - initial list

The following specifications are an initial set of OGC Essential Standards to support 'geospatial components for everyone'.  (Some specs exist, some need to be developed.  Not all are OGC standards)

*   Simple Features for SQL: This standard defines the fundamental geometries and operations which underlie all OGC standards. (though put the 'ODBC/SQL numeric types' stuff in its own 'bronze' spec, no one uses it and its confusing)

*   Well Known Text: This standard started as the text encoding of the Simple Features geometries.  The utility of this approach has spawned extensions outside of the Simple Features standard. (It is already planned as a separate document from current ISO/OGC standards.)

*   Well Known Binary: This is a binary encoding of Well Known Text.  This standard originated as a part of the Simple Features standard.  (with an update for optimized ideas in GeoPackage and TinyWKB)

*   CQL/Filter: Query languages including the Common Query Language from the Catalog standard and the OGC Filter language from the Filter Encoding standard.  (with the geo extensions, originally specified in the CSW spec - for filtering queries: Filter but not in xml)

*   WMTS Simple Tile Matrix:  

*   CSS (CartoCSS is great, though get to interoperable core of 3 renderer implementations)

*   GeoJSON: An extension to the JSON programing language which includes definitions for geometry and coordinate reference system objects.  These definitions are simplified versions of the Simple Feature definitions. (In the wild until IETF is done. Just adopt as is, don't change anything)

*   GeoPackage Features (with a	single set SRID)

*   Simplified GeoPackage Tiles 	(just a direct representation of Simple Tiles scheme above)

*   GML Simple Features Level 0

*   GeoRSS Simple


=== Moving forward on OGC API Essentials

OGC API Essentials could be part of the reworking of OWS Common from an implementer’s perspective.  It would provide a common way to access pieces of OGC capability without having to implement a full OGC interface.  "OWS Common Next Generation" need not look all that different inside if built from this perspective, but what differences there are would have quite an impact. 

Going beyond developing and maintaining an OGC API Essential list, there is additional value in OGC providing a form of concordance between the many and varied representation forms. Along the lines of “this is what a point is comprised of, and here’s how it looks in GeoJSON, here’s how it looks in WKT” and so on.  Users of and developers of map APIs would see value in knowing that there's a common way of representing a point, a line, a polygon and so on within an API's or code library's interface.

OGC can add value and be seen as a go-to for information by defining key geospatial constructs and functionality and being the “cross-walk” to allow people to negotiate between the many and varied way in which these are implemented in the real world.  There would be major value in knowing how to easily transform between differing representations, say, transforming a point in GeoJSON to one in WKT and vice versa and so on. Take a look at the sterling work done with https://github.com/phayes/geoPHP [GeoPHP].


