[preface]
== Preface

OGC defines interfaces that enable interoperability of geospatial applications.
API’s are a popular method to implement interfaces for accessing spatial data.
This White Paper provides a discussion of Application Programming Interfaces (APIs)
to support discussion of possible actions in the Open Geospatial Consortium (OGC).

* Chapter 1 – What is an API?
* Chapter 2 – API Design using Open Standards
* Chapter 3 – OGC API Essentials
* Chapter 4 – Open Standards and APIs.
* Chapter 5 – OGC Support for Open APIs

This is a complex topic.
We have a road of education, discussion, implementation and consensus ahead of us.
This paper aims to help answer questions like:

* If you want to publish geospatial data on the web right now, what are the easiest ways to do so, considering fit-for-purpose?
* If you are developing your API how can you include essential geospatial elements reused from previous best practice?
* How to overcome “walls” of complexity and build on success of “pointy” APIs that are small and simple

**Keywords**

ogcdoc, OGC documents, api, standards

<<<

**Submitters of this document**

All questions regarding this white paper should be directed to the
editor or the submitters:

.Document Contributors
[options="header"]
|=======================
|Name               |Affiliation
|Chris Holmes       |Planet Labs
|Dave Wesloh        |NGA
|Chuck Heazel       |WiSC Enterprises
|Gary Gale          |What 3 Words
|Arnulf Christl     |Metaspatial
|Josh Lieberman     |Tumbling Walls
|Carl Reed          |personal contribution
|John Herring       |Oracle
|David Blodgett     |USGS
|Scott Simmons      |OGC
|Bart de Lathower   |OGC
|George Percivall   |OGC
|=======================
